[2025-01-05T06:35:36.754+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T06:35:36.774+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2025-01-05T06:35:31.059218+00:00 [queued]>
[2025-01-05T06:35:36.784+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2025-01-05T06:35:31.059218+00:00 [queued]>
[2025-01-05T06:35:36.785+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T06:35:36.801+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-01-05 06:35:31.059218+00:00
[2025-01-05T06:35:36.815+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2025-01-05T06:35:31.059218+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp5t5cmqru']
[2025-01-05T06:35:36.813+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1154) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T06:35:36.817+0000] {standard_task_runner.py:105} INFO - Job 83: Subtask is_api_available
[2025-01-05T06:35:36.817+0000] {standard_task_runner.py:72} INFO - Started process 1156 to run task
[2025-01-05T06:35:36.874+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.is_api_available manual__2025-01-05T06:35:31.059218+00:00 [running]> on host a67ecbd59b00
[2025-01-05T06:35:36.975+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T06:35:31.059218+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T06:35:31.059218+00:00'
[2025-01-05T06:35:36.977+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-05T06:35:36.978+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-05T06:35:36.979+0000] {logging_mixin.py:190} INFO - Current task name:is_api_available state:running start_date:2025-01-05 06:35:36.775362+00:00
[2025-01-05T06:35:36.979+0000] {logging_mixin.py:190} INFO - Dag name:user_processing and current dag run status:running
[2025-01-05T06:35:36.980+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T06:35:36.981+0000] {baseoperator.py:416} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-01-05T06:35:36.982+0000] {http.py:137} INFO - Poking: api/
[2025-01-05T06:35:36.991+0000] {base.py:84} INFO - Retrieving connection 'user_api'
[2025-01-05T06:35:38.607+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-01-05T06:35:38.623+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T06:35:38.625+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, run_id=manual__2025-01-05T06:35:31.059218+00:00, execution_date=20250105T063531, start_date=20250105T063536, end_date=20250105T063538
[2025-01-05T06:35:38.644+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-05T06:35:38.645+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-05T06:35:38.646+0000] {logging_mixin.py:190} INFO - Dag name:user_processing queued_at:2025-01-05 06:35:31.078005+00:00
[2025-01-05T06:35:38.647+0000] {logging_mixin.py:190} INFO - Task hostname:a67ecbd59b00 operator:HttpSensor
[2025-01-05T06:35:38.687+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-05T06:35:38.700+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
